export const productsData = {
  "call-of-duty": [
    {
      id: "zenith",
      name: "Zenith",
      price: "From €20.00",
      status: "Undetected",
      statusLevel: "safe",
      media: "https://i.imgur.com/PbDY5pe.mp4",
      description: "Premium cheat with aimbot, ESP, and exclusive features",
      variants: [
        { 
          duration: "1-day", 
          name: "One Day", 
          description: "Perfect for testing", 
          price: "$4.99",
          sellhubVariantId: "dcc91018-acfe-488e-8b58-ebc77e7cb19a"
        },
        { 
          duration: "1-week", 
          name: "1 Week", 
          description: "Short-term access", 
          price: "$14.99",
          sellhubVariantId: "d4b37faf-0983-4251-8704-5170676d0371"
        },
        {
          duration: "1-month",
          name: "1 Month",
          description: "Most popular choice",
          price: "$24.99",
          badge: "POPULAR" as const,
          sellhubVariantId: "0a1dc57f-8ac8-4fe1-b168-b131f9af63bf"
        },
        {
          duration: "lifetime",
          name: "Lifetime",
          description: "One-time payment",
          price: "$50.99",
          badge: "BEST VALUE" as const,
          sellhubVariantId: "81c12347-3f89-41b4-aaeb-eb84c88d17c3"
        },
      ],
    },
    {
      id: "sol-external",
      name: "Sol EXTERNAL",
      price: "From €24.99",
      status: "Undetected",
      statusLevel: "safe",
      media: "https://i.imgur.com/VxXivO3.mp4",
      description: "Advanced cheat with undetected aimbot and ESP",
      variants: [
        { duration: "1-day", name: "One Time", description: "Perfect for testing", price: "$5.99" },
        { duration: "1-week", name: "1 Week", description: "Short-term access", price: "$14.99" },
        {
          duration: "1-month",
          name: "1 Month",
          description: "Most popular choice",
          price: "$29.99",
          badge: "POPULAR" as const,
        },
        {
          duration: "lifetime",
          name: "Lifetime",
          description: "One-time payment",
          price: "$59.99",
          badge: "BEST VALUE" as const,
        },
      ],
    },
    {
      id: "verse-perm-spoofer",
      name: "Verse Perm Spoofer",
      price: "From €19.99",
      status: "Undetected",
      statusLevel: "safe",
      media: "https://i.imgur.com/8bEEyBp.mp4",
      description: "Lifetime HWID protection for all games",
      variants: [
        { duration: "1-day", name: "One Time", description: "Perfect for testing", price: "$14.90" },
        {
          duration: "lifetime",
          name: "Lifetime",
          description: "One-time payment",
          price: "$29.90",
          badge: "BEST VALUE" as const,
        },
      ],
    },
    {
      id: "temp",
      name: "Temp",
      price: "From €29.99",
      status: "Undetected",
      statusLevel: "safe",
      media: "https://i.imgur.com/GY4tjyh.mp4",
      description: "Bypass anti-cheat system completely",
      variants: [
        { duration: "1-day", name: "One Time", description: "Perfect for testing", price: "$4.99" },
        { duration: "1-week", name: "1 Week", description: "Short-term access", price: "$14.99" },
        {
          duration: "1-month",
          name: "1 Month",
          description: "Most popular choice",
          price: "$29.99",
          badge: "POPULAR" as const,
        },
        {
          duration: "lifetime",
          name: "Lifetime",
          description: "One-time payment",
          price: "$49.99",
          badge: "BEST VALUE" as const,
        },
      ],
    },
    {
      id: "phone-verified-steam",
      name: "Phone Verified Steam Accounts",
      price: "Instant Delivery",
      status: "Available",
      statusLevel: "safe",
      media: "https://i.imgur.com/gTrloXO.mp4",
      description: "Temporary HWID spoofing for quick session protection",
      variants: [
        { duration: "1-day", name: "One Time", description: "Perfect for testing", price: "$2.50" },
        { duration: "1-week", name: "1 Week", description: "Short-term access", price: "$8.90" },
        {
          duration: "1-month",
          name: "1 Month",
          description: "Most popular choice",
          price: "$16.49",
          badge: "POPULAR" as const,
        },
        {
          duration: "lifetime",
          name: "Lifetime",
          description: "One-time payment",
          price: "$39.90",
          badge: "BEST VALUE" as const,
        },
      ],
    },
  ],
  valorant: [
    {
      id: "sol-internal",
      name: "Sol Internal",
      price: "From €24.99",
      status: "Undetected",
      statusLevel: "safe",
      media: "https://i.imgur.com/VxXivO3.mp4",
      description: "Advanced internal cheat for Valorant",
      variants: [
        { duration: "1-day", name: "One Time", description: "Perfect for testing", price: "$5.99" },
        { duration: "1-week", name: "1 Week", description: "Short-term access", price: "$14.99" },
        {
          duration: "1-month",
          name: "1 Month",
          description: "Most popular choice",
          price: "$29.99",
          badge: "POPULAR" as const,
        },
        {
          duration: "lifetime",
          name: "Lifetime",
          description: "One-time payment",
          price: "$59.99",
          badge: "BEST VALUE" as const,
        },
      ],
    },
    {
      id: "colorbot",
      name: "ColorBot",
      price: "From €19.99",
      status: "Undetected",
      statusLevel: "safe",
      media: "https://i.imgur.com/VxXivO3.mp4",
      description: "Color-based detection cheat",
      variants: [
        { duration: "1-day", name: "One Time", description: "Perfect for testing", price: "$4.99" },
        { duration: "1-week", name: "1 Week", description: "Short-term access", price: "$12.99" },
        {
          duration: "1-month",
          name: "1 Month",
          description: "Most popular choice",
          price: "$24.99",
          badge: "POPULAR" as const,
        },
      ],
    },
  ],
  roblox: [
    {
      id: "roblox-cheat-1",
      name: "Roblox ESP",
      price: "From €15.99",
      status: "Undetected",
      statusLevel: "safe",
      media: "https://i.imgur.com/VxXivO3.mp4",
      description: "Roblox ESP cheat with multiple features",
      variants: [
        { duration: "1-day", name: "One Time", description: "Perfect for testing", price: "$3.99" },
        { duration: "1-week", name: "1 Week", description: "Short-term access", price: "$9.99" },
      ],
    },
  ],
  "rocket-league": [
    {
      id: "rl-cheat-1",
      name: "Rocket League Speed",
      price: "From €18.99",
      status: "Undetected",
      statusLevel: "safe",
      media: "https://i.imgur.com/8bEEyBp.mp4",
      description: "Speed hack for Rocket League",
      variants: [
        { duration: "1-day", name: "One Time", description: "Perfect for testing", price: "$4.99" },
        { duration: "1-week", name: "1 Week", description: "Short-term access", price: "$11.99" },
      ],
    },
  ],
  "rainbow-six-siege-x": [
    {
      id: "r6-cheat-1",
      name: "R6 ESP",
      price: "From €22.99",
      status: "Undetected",
      statusLevel: "safe",
      media: "https://i.imgur.com/8bEEyBp.mp4",
      description: "Rainbow Six Siege ESP cheat",
      variants: [
        { duration: "1-day", name: "One Time", description: "Perfect for testing", price: "$5.99" },
        { duration: "1-week", name: "1 Week", description: "Short-term access", price: "$13.99" },
      ],
    },
  ],
}
